package io.github.flyaif.gruvbox.generator

data class UiTheme(
    val name: String,
    val dark: Boolean,
    val author: String,
    val editorSchemePath: String,
    /** Named colors; `ui` and `icons` reference these by name. */
    val colors: Map<String, String>,
    val ui: Map<String, Any>,
    val icons: Map<String, Any>,
)

fun uiThemeFor(variant: Variant): UiTheme = with(Palette) {
    val bg0 = variant.bg0

    val colors = linkedMapOf(
        // backgrounds: bg0 follows the Contrast Level, everything else is shared
        "bg0" to bg0.hex,
        "bg0TintRed" to neutralRed.blendOver(bg0, 0.15).hex,
        "bg0TintGreen" to neutralGreen.blendOver(bg0, 0.15).hex,
        "bg0TintYellow" to neutralYellow.blendOver(bg0, 0.15).hex,
        "bg0TintBlue" to neutralBlue.blendOver(bg0, 0.15).hex,
        "bg0TintPurple" to neutralPurple.blendOver(bg0, 0.15).hex,
        "bg0TintOrange" to neutralOrange.blendOver(bg0, 0.15).hex,
        "bg1" to bg1.hex,
        "bg2" to bg2.hex,
        "bg3" to bg3.hex,
        "bg4" to bg4.hex,
        "gray" to gray.hex,
        "fg0" to fg0.hex,
        "fg1" to fg1.hex,
        "fg2" to fg2.hex,
        "fg3" to fg3.hex,
        "fg4" to fg4.hex,
        "red" to brightRed.hex,
        "green" to brightGreen.hex,
        "yellow" to brightYellow.hex,
        "blue" to brightBlue.hex,
        "purple" to brightPurple.hex,
        "aqua" to brightAqua.hex,
        "orange" to brightOrange.hex,
        "redDim" to neutralRed.hex,
        "greenDim" to neutralGreen.hex,
        "yellowDim" to neutralYellow.hex,
        "blueDim" to neutralBlue.hex,
        "purpleDim" to neutralPurple.hex,
        "aquaDim" to neutralAqua.hex,
        "orangeDim" to neutralOrange.hex,
        "redFaded" to fadedRed.hex,
        "yellowFaded" to fadedYellow.hex,
        "blueFaded" to fadedBlue.hex,
        "orangeFaded" to fadedOrange.hex,
    )

    val ui = linkedMapOf<String, Any>(
        "*" to linkedMapOf<String, Any>(
            "background" to "bg0",
            "foreground" to "fg1",
            "infoForeground" to "fg4",
            "selectionBackground" to "bg2",
            "selectionForeground" to "fg0",
            "selectionInactiveBackground" to "bg1",
            "disabledForeground" to "bg4",
            "disabledText" to "bg4",
            "borderColor" to "bg1",
            "disabledBorderColor" to "bg1",
            "focusedBorderColor" to "bg4",
            "focusColor" to "orange",
            "separatorColor" to "bg1",
            "lineSeparatorColor" to "bg1",
            "acceleratorForeground" to "orange",
            "acceleratorSelectionForeground" to "fg0",
            "errorForeground" to "red",
            "hoverBackground" to "bg1",
            "modifiedItemForeground" to "aqua",
        ),
        "ActionButton" to linkedMapOf(
            "hoverBackground" to "bg1",
            "hoverBorderColor" to "bg1",
            "pressedBackground" to "bg2",
            "pressedBorderColor" to "bg2",
        ),
        "Borders" to linkedMapOf(
            "color" to "bg1",
            "ContrastBorderColor" to "bg1",
        ),
        "Button" to linkedMapOf(
            "foreground" to "fg1",
            "startBackground" to "bg1",
            "endBackground" to "bg1",
            "startBorderColor" to "bg3",
            "endBorderColor" to "bg3",
            "default" to linkedMapOf(
                "foreground" to "fg0",
                "startBackground" to "orangeFaded",
                "endBackground" to "orangeFaded",
                "startBorderColor" to "orangeFaded",
                "endBorderColor" to "orangeFaded",
                "focusedBorderColor" to "orange",
            ),
        ),
        "ComboBox" to linkedMapOf(
            "nonEditableBackground" to "bg1",
            "ArrowButton.background" to "bg1",
            "ArrowButton.nonEditableBackground" to "bg1",
            "ArrowButton.iconColor" to "fg3",
        ),
        "CompletionPopup" to linkedMapOf(
            "selectionBackground" to "bg2",
            "selectionInactiveBackground" to "bg1",
            "matchForeground" to "orange",
        ),
        "Component" to linkedMapOf(
            "borderColor" to "bg2",
            "focusedBorderColor" to "bg4",
            "focusColor" to "orange",
            "errorFocusColor" to "red",
            "inactiveErrorFocusColor" to "redFaded",
            "warningFocusColor" to "yellow",
            "inactiveWarningFocusColor" to "yellowFaded",
        ),
        "Counter" to linkedMapOf(
            "background" to "blueDim",
            "foreground" to "fg0",
        ),
        "DefaultTabs" to linkedMapOf(
            "background" to "bg0",
            "hoverBackground" to "bg1",
            "underlinedTabBackground" to "bg1",
            "underlineColor" to "orange",
            "inactiveUnderlineColor" to "bg4",
        ),
        "DragAndDrop" to linkedMapOf(
            "borderColor" to "orange",
        ),
        "Editor" to linkedMapOf(
            "background" to "bg0",
            "foreground" to "fg1",
            "shortcutForeground" to "orange",
        ),
        "EditorTabs" to linkedMapOf(
            "background" to "bg0",
            "hoverBackground" to "bg1",
            "underlinedTabBackground" to "bg1",
            "underlineColor" to "orange",
            "inactiveUnderlineColor" to "bg4",
            "borderColor" to "bg1",
        ),
        "FileColor" to linkedMapOf(
            "Yellow" to "bg0TintYellow",
            "Green" to "bg0TintGreen",
            "Blue" to "bg0TintBlue",
            "Violet" to "bg0TintPurple",
            "Orange" to "bg0TintOrange",
            "Rose" to "bg0TintRed",
        ),
        "Link" to linkedMapOf(
            "activeForeground" to "blue",
            "hoverForeground" to "blue",
            "visitedForeground" to "purple",
            "pressedForeground" to "orange",
        ),
        "List" to linkedMapOf(
            "background" to "bg0",
            "hoverBackground" to "bg1",
            "hoverInactiveBackground" to "bg1",
        ),
        "MainToolbar" to linkedMapOf(
            "background" to "bg0",
            "Dropdown.hoverBackground" to "bg1",
            "Dropdown.pressedBackground" to "bg2",
            "Icon.hoverBackground" to "bg1",
            "Icon.pressedBackground" to "bg2",
        ),
        "Menu" to linkedMapOf(
            "background" to "bg0",
            "borderColor" to "bg2",
        ),
        "NavBar" to linkedMapOf(
            "borderColor" to "bg1",
        ),
        "Notification" to linkedMapOf(
            "background" to "bg1",
            "borderColor" to "bg3",
            "errorBorderColor" to "red",
        ),
        "Panel" to linkedMapOf(
            "background" to "bg0",
        ),
        "Popup" to linkedMapOf(
            "borderColor" to "bg2",
            "separatorColor" to "bg2",
            "Header.activeBackground" to "bg1",
            "Header.inactiveBackground" to "bg1",
            "Advertiser.background" to "bg1",
        ),
        "ProgressBar" to linkedMapOf(
            "progressColor" to "orange",
            "indeterminateStartColor" to "orangeDim",
            "indeterminateEndColor" to "orange",
            "trackColor" to "bg2",
            "failedColor" to "redDim",
            "failedEndColor" to "red",
            "passedColor" to "greenDim",
            "passedEndColor" to "green",
        ),
        "SearchEverywhere" to linkedMapOf(
            "Header.background" to "bg1",
            "SearchField.background" to "bg0",
            "SearchField.borderColor" to "bg2",
            "Tab.selectedBackground" to "bg2",
            "Tab.selectedForeground" to "fg0",
        ),
        "SearchMatch" to linkedMapOf(
            "startBackground" to "yellowDim",
            "endBackground" to "yellowDim",
        ),
        "SpeedSearch" to linkedMapOf(
            "background" to "bg1",
            "foreground" to "fg1",
            "borderColor" to "bg3",
            "errorForeground" to "red",
        ),
        "StatusBar" to linkedMapOf(
            "background" to "bg0",
            "borderColor" to "bg1",
            "Widget.hoverBackground" to "bg1",
            "Widget.pressedBackground" to "bg2",
        ),
        "TabbedPane" to linkedMapOf(
            "underlineColor" to "orange",
            "hoverColor" to "bg1",
            "focusColor" to "bg2",
            "contentAreaColor" to "bg1",
        ),
        "Table" to linkedMapOf(
            "background" to "bg0",
            "gridColor" to "bg1",
            "stripeColor" to "bg1",
            "hoverBackground" to "bg1",
        ),
        "TableHeader" to linkedMapOf(
            "background" to "bg0",
            "bottomSeparatorColor" to "bg1",
        ),
        "TextField" to linkedMapOf(
            "background" to "bg0",
        ),
        "TextArea" to linkedMapOf(
            "background" to "bg0",
        ),
        "ToolTip" to linkedMapOf(
            "background" to "bg1",
            "foreground" to "fg1",
            "borderColor" to "bg3",
            "shortcutForeground" to "orange",
        ),
        "ToolWindow" to linkedMapOf(
            "background" to "bg0",
            "Header.background" to "bg0",
            "Header.inactiveBackground" to "bg0",
            "Header.borderColor" to "bg1",
            "HeaderTab.hoverBackground" to "bg1",
            "HeaderTab.selectedBackground" to "bg2",
            "HeaderTab.selectedInactiveBackground" to "bg1",
            "Button.hoverBackground" to "bg1",
            "Button.selectedBackground" to "bg2",
            "Button.selectedForeground" to "fg0",
        ),
        "Tree" to linkedMapOf(
            "background" to "bg0",
            "hoverBackground" to "bg1",
            "modifiedItemForeground" to "aqua",
        ),
        "VersionControl" to linkedMapOf(
            "GitLog.headIconColor" to "yellow",
            "GitLog.localBranchIconColor" to "green",
            "GitLog.remoteBranchIconColor" to "orange",
            "GitLog.tagIconColor" to "fg3",
            "Log.Commit.hoveredBackground" to "bg1",
            "RefLabel.foreground" to "fg1",
        ),
    )

    val icons = linkedMapOf<String, Any>(
        "ColorPalette" to linkedMapOf(
            "Checkbox.Background.Default.Dark" to bg1.hex,
            "Checkbox.Border.Default.Dark" to bg3.hex,
            "Checkbox.Background.Selected.Dark" to neutralOrange.hex,
            "Checkbox.Border.Selected.Dark" to neutralOrange.hex,
            "Checkbox.Foreground.Selected.Dark" to fg0.hex,
            "Checkbox.Focus.Wide.Dark" to brightOrange.hex,
            "Checkbox.Focus.Thin.Default.Dark" to bg4.hex,
            "Checkbox.Focus.Thin.Selected.Dark" to brightOrange.hex,
            "Checkbox.Background.Disabled.Dark" to bg1.hex,
            "Checkbox.Border.Disabled.Dark" to bg2.hex,
            "Checkbox.Foreground.Disabled.Dark" to bg4.hex,
            "Actions.Red" to brightRed.hex,
            "Actions.Yellow" to brightYellow.hex,
            "Actions.Green" to brightGreen.hex,
            "Actions.Blue" to brightBlue.hex,
            "Actions.Grey" to gray.hex,
            "Actions.GreyInline.Dark" to fg4.hex,
            "Objects.Grey" to gray.hex,
            "Objects.Red" to brightRed.hex,
            "Objects.RedStatus" to neutralRed.hex,
            "Objects.Pink" to brightPurple.hex,
            "Objects.Yellow" to brightYellow.hex,
            "Objects.YellowDark" to neutralYellow.hex,
            "Objects.Green" to brightGreen.hex,
            "Objects.GreenAndroid" to brightGreen.hex,
            "Objects.Blue" to brightBlue.hex,
            "Objects.Purple" to brightPurple.hex,
            // text drawn on colored object icons; fixed medium bg0 on purpose —
            // it must contrast with the icon fill, not match the editor background
            "Objects.BlackText" to Palette.bg0.hex,
        ),
    )

    UiTheme(
        name = variant.displayName,
        dark = true,
        author = "flyaif",
        editorSchemePath = "/themes/${variant.fileStem}.xml",
        colors = colors,
        ui = ui,
        icons = icons,
    )
}
